site_name: PLATAFORMA
site_url: http://172.16.14.30:8000
site_author: Miguel y Teddy
site_description: Documentación Manual de PLATAFORMA

theme:
  name: material
  language: es
  logo: assets/logoByte.png
  palette:
    - scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  font:
    text: Roboto # "Fancy" no es una fuente estándar, Roboto es la recomendada
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy # Muy útil para manuales técnicos

copyright: "© 2026 Byte"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

nav:
  - Menu Pricipal: index.md
  - Estándares: estandares/index.md
  - Configuración: configuraciones/index.md
  - Autorizaciones: autorizaciones/index.md
  - Búsqueda de cliente: 
        - Introducción Busqueda de cliete: busqueda-clientes/busqueda-clientes.md
        - Tipos de Búsqueda Disponibles:
            - Búsqueda por Documento de Identificación: busqueda-clientes/busqueda-documento.md
            - Búsqueda por Código de cliente: busqueda-clientes/busqueda-codigo.md       
            - Búsqueda por Nombres: busqueda-clientes/busqueda-nombres.md       
            - Búsqueda por Producto: busqueda-clientes/busqueda-producto.md       
            - Criterios: busqueda-clientes/criterios.md       
  - Crear Cliente:
        - Introducción Crear Cliente: crear-cliente/crear-cliente.md
        - Tipos de Creacion:
            - Crear cliente - Persona Natural: crear-cliente/crear-cliente-natural.md
            - Crear cliente - Persona Jurídica: crear-cliente/crear-cliente-juridica.md  
            - Crear Usuario: crear-cliente/crear-usuario.md       
  - Administrar Persona:
        - Introducción Administrar Persona: tablas-contenido-1.md
        - Tablas de contenido 2:
            - Introducción: tablas-contenido-2.md
            - Tablas de contenido 2.1: tablas-contenido-2-1.md       