site_name: Documentación JTeller

nav:
  - Inicio: index.md
  - Jteller:
      - Operation-view:
          - Inicio Operation-view: operation-view.md
          - Dashboard:
              - Dashboard Operativo: Dashboard Operativo.md
          - Transacciones:
              - Transacciones: transacciones.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md
      - Specs-View:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md
      - Firmas:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md
      - Distribuidor:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md
  - Convenios:
      - Funciones Generales:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md      
      - Operaciones:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md                                          

theme:
  name: material
  logo: assets/logo.png
  # favicon: assets/favicon.ico
  palette:
    - scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  font:
    text: Roboto # "Fancy" no es una fuente estándar, Roboto es la recomendada
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy # Muy útil para manuales técnicos

copyright: "© 2024 Byte"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css