site_name: PLATAFORMA

nav:
    - Menu Pricipal: index.md
    - Estándares: estandares/index.md
    - Configuración: configuraciones/index.md
    - Autorizaciones: autorizaciones/index.md
    - Búsqueda de cliente: 
          - Introducción: tablas-contenido-1.md
          - Tipos de Búsqueda Disponibles:
              - Búsqueda por Documento de Identificación: tablas-contenido-2.md
              - Búsqueda por Código de cliente: tablas-contenido-2-1.md       
              - Búsqueda por Nombres: tablas-contenido-2-1.md       
              - Búsqueda por Producto: tablas-contenido-2-1.md       
              - Criterios: tablas-contenido-2-1.md       
    - Crear Cliente:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md       
    - Administrar Persona:
          - Introducción: tablas-contenido-1.md
          - Tablas de contenido 2:
              - Introducción: tablas-contenido-2.md
              - Tablas de contenido 2.1: tablas-contenido-2-1.md       


theme:
  name: material
  logo: assets/logoByte.png
  # favicon: assets/favicon.ico
  palette:
    - scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  font:
    text: Roboto # "Fancy" no es una fuente estándar, Roboto es la recomendada
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy # Muy útil para manuales técnicos

copyright: "© 2024 Byte"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css